name: Deploy Laravel App

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.SERVER_SSH_KEY }}

      - name: Deploy to Server
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }} << 'EOF'
            cd /www/wwwroot/nam.gold

            echo "👉 Pull latest code..."
            git config --global --add safe.directory /www/wwwroot/nam.gold
            git reset --hard
            git pull origin main

            echo "👉 Restore .env if missing..."
            if [ ! -f .env ]; then
              cp /www/wwwroot/nam.gold/.env.example /www/wwwroot/nam.gold/.env
            fi

            echo "👉 Fix permissions..."
            chmod -R 775 storage bootstrap/cache || true
            touch storage/logs/laravel.log || true
            chmod 664 storage/logs/laravel.log || true


            echo "👉 Install dependencies..."
            composer install --no-interaction --prefer-dist --optimize-autoloader || true

            echo "👉 Run migrations..."
            php artisan migrate --force || true

            echo "👉 Clear cache..."
            php artisan config:clear || true
            php artisan cache:clear || true
            php artisan route:clear || true
            php artisan view:clear || true

            echo "👉 Restart web server..."
            sudo bt restart || true
          EOF
